// This file is generated by FlutterFire CLI.
// Manually updated with real credentials from google-services.json
// Project: swsaidocanalyzer

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not supported');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Unsupported platform');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyX-AwjkxDc2-3iBmRannRCUKJ31hjTYE',
    appId: '1:50362085656:android:92346dd68685ec8485ee6d',
    messagingSenderId: '50362085656',
    projectId: 'swsaidocanalyzer',
    storageBucket: 'swsaidocanalyzer.firebasestorage.app',
  );

  // iOS: replace with real values from GoogleService-Info.plist if needed
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyX-AwjkxDc2-3iBmRannRCUKJ31hjTYE',
    appId: '1:50362085656:android:92346dd68685ec8485ee6d',
    messagingSenderId: '50362085656',
    projectId: 'swsaidocanalyzer',
    storageBucket: 'swsaidocanalyzer.firebasestorage.app',
    iosBundleId: 'com.fnext.swsaianalyzer',
  );
}

