// This file is generated by FlutterFire CLI.
// Run: flutterfire configure --project=sws-ai-docs
// Then replace this file with the generated output.
//
// For reviewers: run `flutterfire configure` with your own Firebase project
// and replace this file. See README for full setup steps.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not supported');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Unsupported platform');
    }
  }

  // ─── REPLACE these values with your own Firebase project credentials ───
  // Run: flutterfire configure --project=YOUR_PROJECT_ID
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'sws-ai-docs',
    storageBucket: 'sws-ai-docs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'sws-ai-docs',
    storageBucket: 'sws-ai-docs.appspot.com',
    iosBundleId: 'com.swsai.docmanager',
  );
}
